```plantuml
@startuml

'!theme spacelab
!theme sandstone


skinparam noteFontColor grey
skinparam noteBackgroundColor #FFF8E1
skinparam noteBorderColor #FFAB00


header
<font color=grey>Scanframe Docker CI/CD</font>
endheader

footer
<font color=grey>C++ Builder Process - %date("yyyy-MM-dd")</font>
endfooter

title "=== C++ Build Docker Images Process\nWith and Without Qt Libraries"

start
:= Create C++ Builder images
using [[https://git.scanframe.com/docker/gitlab-runner/-/blob/main/cpp-builder.sh cpp-builder.sh]] script;


partition "= Base Image\n//(Secure in private registry)//" {
	:Select upstream base image(s)\n//(e.g., amd64/ubuntu:24.04)//;
	fork
		:Pull for amd64;
	fork again
		:Pull for arm64/aarch64;
	end fork
	:Tag as <private-registry>/<arch>/<base>:<os-ver>\n//(e.g., nexus.scanframe.com/amd64/ubuntu:24.04)//;
	:Push to the private registry;
	note right
		Result: Trusted, versioned base
		available internally per architecture.
	end note
}

partition "= C++ Builder Image\n//(For building the Qt framework)//" {
	:Build "C++toolchain" image from internal base\n//(e.g. amd64/ubuntu:24.04)//;
	:Run image build script\nwhich installs all required build tools.\n //(like: gcc/g++, cmake, ninja, gdb, clang-format,//\n//MinGW cross, aarch64 cross, Python3, etc.)//;
	:Push C++ builder image to private registry\n//(e.g. nexus.scanframe.com/amd64/ubuntu:24.04)//;
	note right
		Purpose: Reusable base to build Qt from source
		inside containers and to build non‑Qt apps.
	end note
}

partition "= Prepare Qt Libraries\n//(Artifacts in Private Storage)//" {
	fork
		partition "=== Linux Native\n//(containerized)//\nlnx-x86_64, lnx-aarch64\ngnu_64" {
			:Start container from\nnon‑Qt builder per architecture;
			:Run [[https://git.scanframe.com/docker/gitlab-runner/-/blob/main/build-qt-lib.sh build-qt-lib.sh]]\nto build native libraries;
		}
	fork again
		partition "=== Linux Cross-Compile\n//(containerized)//\nwin-x86_64\nmingw_64" {
			:Start container from\nnon‑Qt builder (amd64);
			:Run [[https://git.scanframe.com/docker/gitlab-runner/-/blob/main/build-qt-lib.sh build-qt-lib.sh]]\nwith **--windows**;
		}
	fork again
		partition "=== Windows Native\n//(native)//\nw64-x86_64\nmingw_64, msvc_64" {
			:Install [[https://git.scanframe.com/shared/bin-bash Cygwin and Scripts]];
			:Install MinGW and/or MSVC toolchains;
			:Run [[https://git.scanframe.com/docker/gitlab-runner/-/blob/main/build-qt-lib.sh build-qt-lib.sh]]\nfor native Windows builds;
		}
	end fork

	:Upload Qt libraries to [[https://nexus.scanframe.com/#browse/browse:shared:library%2Fqt Nexus]] private storage;
	note right
	* library/qt/lnx-aarch64/<ver>/gcc_64
	* library/qt/lnx-x86_64/<ver>/gcc_64
	* library/qt/w64-x86_64/<ver>/(mingw_64, msvc_64)
	* library/qt/win-x86_64/<ver>/mingw_64
	end note
}

partition "= C++ Qt Builder Images\n//(containerized)//" {
	:Build Qt-enabled image(s) per arch from non‑Qt base;
	:Fetch Qt compressed files from [[https://nexus.scanframe.com/#browse/browse:shared:library%2Fqt private storage]]
	 //(lnx-x86_64, lnx-aarch64, win-x86_64, w64-x86_64)//	 ;

	:Push Qt C++ Builder image(s) to the [[https://nexus.scanframe.com/#browse/browse:docker-image:v2%2Famd64%2Fgnu-cpp%2Ftags private registry]];
}

partition "= Mirror/Publish\n//Docker Hub//" {
	note left
		Optional
	end note
	:Login to Docker Hub (CI secret);
	:Push images per architecture;
	:Optionally push 'latest' tag;
	:Update SBOM in public registry;
}

stop
@enduml
```