concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Docker"
  url = "<gitlab-url>"
  token = "<gitlab-token>"
  token_obtained_at = 2024-01-26T19:52:16Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  environment = ["BIND_DIR=/tmp/binder"]
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    image = "nexus.scanframe.com:8090/gnu-cpp:dev"
    tls_verify = false
    pull_policy = "if-not-present"
    # Needed for fuse.
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
